import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const localeFiles = {
  en: "public/_locales/en/messages.json",
  zh_CN: "public/_locales/zh_CN/messages.json",
};
const outputPath = resolve(rootDir, "src/shared/i18n.generated.ts");

async function readLocale(relativePath) {
  const raw = await readFile(resolve(rootDir, relativePath), "utf-8");
  return JSON.parse(raw);
}

function toMessageMap(localeName, localeMessages) {
  const entries = Object.entries(localeMessages);

  if (entries.length === 0) {
    throw new Error(`${localeName} has no messages`);
  }

  return Object.fromEntries(
    entries.map(([key, value]) => {
      if (!value || typeof value.message !== "string") {
        throw new Error(`${localeName}.${key} must define a string message`);
      }

      return [key, value.message];
    }),
  );
}

function assertMatchingKeys(locales) {
  const [baseLocale, baseMessages] = Object.entries(locales)[0];
  const baseKeys = Object.keys(baseMessages).sort();

  for (const [localeName, messages] of Object.entries(locales).slice(1)) {
    const keys = Object.keys(messages).sort();
    if (JSON.stringify(keys) !== JSON.stringify(baseKeys)) {
      throw new Error(
        `${localeName} message keys do not match ${baseLocale} message keys`,
      );
    }
  }
}

async function main() {
  const locales = {};

  for (const [localeName, relativePath] of Object.entries(localeFiles)) {
    locales[localeName] = toMessageMap(
      localeName,
      await readLocale(relativePath),
    );
  }

  assertMatchingKeys(locales);

  const source = `// This file is generated by scripts/generate-i18n.mjs.
// Edit public/_locales/*/messages.json, then run npm test/dev/build.

export const MESSAGES = ${JSON.stringify(locales, null, 2)} as const;
`;

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
}

await main();
